{'data': {'formInfo': {'widgetMap': {
    '_S_INT_ON_BUSINESS_REASON': {'codeId': '_S_INT_ON_BUSINESS_REASON', 'extendFieldMap': {}, 'title': '出差事由',
                                  'type': 'textAreaWidget', 'value': '测试出差'},
    'Ra_0': {'codeId': 'Ra_0', 'extendFieldMap': {}, 'displaylinkageVos': [{'additional': {
        'state': {'label': '必填', 'value': 'required'}, 'option': [{'label': '生产/品保一线人员', 'value': 'AaBaCcDd'}],
        'target': {'label': '班组长', 'value': 'Ps_1'}}, 'rule': {'or': [{'eq': 'AaBaCcDd'}]}, 'behavior': {
        'Ps_1': {'state': 'required'}}}, {'additional': {'state': {'label': '隐藏', 'value': 'hidden'},
                                                         'option': [{'label': '非生产/品保一线人员', 'value': 'EeFfGgHh'}],
                                                         'target': {'label': '班组长', 'value': 'Ps_1'}},
                                          'rule': {'or': [{'eq': 'EeFfGgHh'}]},
                                          'behavior': {'Ps_1': {'state': 'hidden'}}}],
             'options': [{'checked': "False", 'value': '生产/品保一线人员', 'key': 'AaBaCcDd'},
                         {'checked': "False", 'value': '非生产/品保一线人员', 'key': 'EeFfGgHh'}], 'linkRule': [], 'title': '人员类别',
             'type': 'radioWidget', 'value': 'EeFfGgHh'},
    '_S_APPLY': {'eid': '19469603', 'codeId': '_S_APPLY', 'existEcosphere': "False", 'title': '提交人',
                 'type': 'personSelectWidget', 'personInfo': [
            {'image': 'https://static.yunzhijia.com/space/c/photo/load?id=60d59879fc15d6000143ffae',
             'companyName': '江苏谷登重型机械装备科技有限公司', 'jobTitle': 'ERP专员', 'name': '周为',
             'deptLongName': '江苏谷登重型机械装备科技有限公司/审计部', 'oid': '5f2e53bce4b0ce6aad23fa1e', 'dept': '审计部',
             'userId': '5f2686c2e4b0aa487b634a9c'}], 'value': ['5f2e53bce4b0ce6aad23fa1e']},
    'Ps_0': {'eid': '19469603', 'codeId': 'Ps_0', 'roleIds': [], 'extendFieldMap': {}, 'existEcosphere': "False",
             'optSource': 'org', 'title': '同行人员', 'type': 'personSelectWidget', 'personInfo': [], 'value': [],
             'option': 'multi'},
    'Ps_1': {'eid': '19469603', 'codeId': 'Ps_1', 'roleIds': [], 'extendFieldMap': {}, 'existEcosphere': "False",
             'optSource': 'org', 'title': '班组长', 'type': 'personSelectWidget', 'personInfo': [], 'option': 'single'},
    '_S_SERIAL': {'codeId': '_S_SERIAL', 'extendFieldMap': {}, 'title': '流水号', 'type': 'serialNumWidget',
                  'value': 'CSCCSQD-20210901-003'},
    '_S_DATE': {'codeId': '_S_DATE', 'fromNowOn': "False", 'title': '申请日期', 'type': 'dateWidget', 'value': 1630482429493},
    'Im_0': {'codeId': 'Im_0', 'extendFieldMap': {}, 'maximum': 200, 'title': '图片', 'type': 'imageWidget', 'value': []},
    'Ta_0': {'codeId': 'Ta_0', 'extendFieldMap': {}, 'title': '说明', 'type': 'textAreaWidget', 'value': ''},
    '_S_INT_ON_BUSINESS_DESC': {'codeId': '_S_INT_ON_BUSINESS_DESC', 'describeFileVos': [], 'extendFieldMap': {},
                                'title': '说明文字', 'type': 'describeWidget'},
    'At_0': {'codeId': 'At_0', 'extendFieldMap': {}, 'maximum': 200, 'title': '文件', 'type': 'attachmentWidget',
             'value': []},
    '_S_DEPT': {'eid': '19469603', 'codeId': '_S_DEPT', 'title': '所属部门', 'type': 'departmentSelectWidget', 'deptInfo': [
        {'name': '审计部', 'orgId': 'b3a83a19-f95a-11ea-a634-ecf4bbea149a', 'realLongName': '江苏谷登重型机械装备科技有限公司!审计部',
         'longName': '审计部'}], 'selectCompanyOnly': "False", 'value': ['b3a83a19-f95a-11ea-a634-ecf4bbea149a']},
    '_S_TITLE': {'codeId': '_S_TITLE', 'extendFieldMap': {'titleEntity': {'kind': 'TITLE_DEFAULT', 'list': [
        {'formItem': '_S_APPLY', 'kind': 'ITEM_FORM_ITEM'}, {'formItem': '的', 'kind': 'ITEM_STRING'},
        {'formItem': '模板名称', 'kind': 'ITEM_TEMPLATENAME'}]}, 'defaultTitle': "True"}, 'title': '标题',
                 'type': 'textWidget', 'value': '周为的测试出差申请单'}}, 'detailMap': {
    '_S_INT_ON_BUSINESS_DETAILED': {'buttonName': '添加出差明细', 'codeId': '_S_INT_ON_BUSINESS_DETAILED', 'widgetVos': {
        '_S_INT_ON_BUSINESS_DAYS': {'codeId': '_S_INT_ON_BUSINESS_DAYS', 'decimalDigit': 2, 'extendFieldMap': {},
                                    'detailCountName': '出差总天数', 'title': '出差天数', 'type': 'numberWidget',
                                    'detailCount': "True"},
        '_S_INT_ON_BUSINESS_DESTINATION': {'codeId': '_S_INT_ON_BUSINESS_DESTINATION', 'extendFieldMap': {},
                                           'title': '目的地', 'type': 'textWidget'},
        'Te_8': {'codeId': 'Te_8', 'extendFieldMap': {'wordLimit': 200}, 'title': '备注', 'type': 'textWidget'},
        'Te_7': {'codeId': 'Te_7', 'extendFieldMap': {'wordLimit': 200}, 'title': '出发地', 'type': 'textWidget'},
        '_S_INT_ON_BUSINESS_TIME': {'codeId': '_S_INT_ON_BUSINESS_TIME', 'dateFormat': 'yyyy-MM-dd HH:mm',
                                    'extendFieldMap': {}, 'fromNowOn': "False", 'title2': '结束时间', 'title': '开始时间',
                                    'type': 'dateRangeWidget'}},
                                    'extendFieldMap': {'showSerialNum': "False", 'bookTicket': "False"}, 'widgetValue': [
            {'_S_INT_ON_BUSINESS_DAYS': '1', '_S_INT_ON_BUSINESS_DESTINATION': '测试', '_id_': '1', 'Te_8': '',
             'Te_7': '', '_S_INT_ON_BUSINESS_TIME': [1630454400000, 1630488600000]},
            {'_S_INT_ON_BUSINESS_DAYS': '2', '_S_INT_ON_BUSINESS_DESTINATION': '测试', '_id_': '2', 'Te_8': '',
             'Te_7': '', '_S_INT_ON_BUSINESS_TIME': [1630598400000, 1630771200000]}], 'imageInfo': {},
                                    'title': '实际出差行程', 'type': 'detailedWidget'}}},
          'basicInfo': {'nodeName': '完成审批', 'eid': '19469603', 'eventId': 'eed8ecad-87a7-4e56-806c-9a445f08255e',
                        'formDefId': '612f2f1f830c4a0001c165b3', 'dataType': 1,
                        'myNetworkInfo': {'eid': '19469603', 'name': '江苏谷登重型机械装备科技有限公司'}, 'nodeType': 'END',
                        'title': '测试出差申请单', 'flowInstId': '612f2ffdff8fb6000112b3d4',
                        'formCodeId': '2cb666506e2f4c789b96941d9d3f4777', 'actionType': 'reach', 'myPersonInfo': {
                  'image': 'https://static.yunzhijia.com/space/c/photo/load?id=60d59879fc15d6000143ffae',
                  'jobNo': '20080103', 'name': '周为', 'oid': '5f2e53bce4b0ce6aad23fa1e'},
                        'formInstId': '612f2ffda733d400015fdc56', 'eventTime': 1630482430082,
                        'myDeptInfo': {'name': '审计部', 'orgId': 'b3a83a19-f95a-11ea-a634-ecf4bbea149a'},
                        'interfaceId': 'CRvPVtva', 'interfaceName': '出差', 'returned': "False",
                        'nodeId': '612f2ffdff8fb6000112b3ef'}}, 'success': "True", 'errorCode': 0}
