# Generated by Django 3.2.7 on 2021-09-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttsystemTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'attsystem_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('years', models.IntegerField(blank=True, null=True, verbose_name='年')),
                ('months', models.IntegerField(blank=True, null=True, verbose_name='月')),
                ('days', models.IntegerField(blank=True, null=True, verbose_name='日')),
                ('weeks', models.IntegerField(blank=True, null=True, verbose_name='周几')),
                ('kinds', models.IntegerField(blank=True, choices=[(1, '普通工作日'), (2, '周六工作日'), (3, '周日'), (4, '节假日')], null=True, verbose_name='类型')),
            ],
            options={
                'verbose_name': '工作日历',
                'db_table': 'cal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckInDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(verbose_name='刷卡日期')),
                ('checkin_time', models.TimeField(verbose_name='刷卡时间')),
                ('weeks', models.IntegerField(verbose_name='周几')),
                ('years', models.IntegerField(blank=True, null=True)),
                ('months', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '刷卡流水表',
                'db_table': 'check_in_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeBustravelStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bustravel_start_time', models.TimeField(blank=True, null=True, verbose_name='出差开始时间')),
                ('bustravel_stop_time', models.TimeField(blank=True, null=True, verbose_name='出差结束时间')),
                ('bustravel_last_time', models.FloatField(verbose_name='出差时长(天)')),
                ('years', models.IntegerField(blank=True, null=True)),
                ('months', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('weeks', models.IntegerField(blank=True, null=True)),
                ('dates', models.DateField(blank=True, null=True, verbose_name='出差日期')),
                ('serial', models.CharField(blank=True, max_length=255, null=True, verbose_name='云之家流水号')),
                ('go_out_type', models.IntegerField(blank=True, choices=[(1, '公干'), (2, '出差')], null=True, verbose_name='出门类型')),
            ],
            options={
                'verbose_name': '出差信息统计表',
                'db_table': 'employee_bustravel_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDaysStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.TimeField(blank=True, null=True, verbose_name='上班刷卡时间')),
                ('out_time', models.TimeField(blank=True, null=True, verbose_name='下班刷卡时间')),
                ('judge_in_time', models.TimeField(blank=True, null=True, verbose_name='标定上班刷卡时间')),
                ('judge_out_time', models.TimeField(blank=True, null=True, verbose_name='标定下班刷卡时间')),
                ('act_times', models.FloatField(blank=True, null=True, verbose_name='实际出勤(天)')),
                ('holi_in_time', models.TimeField(blank=True, null=True, verbose_name='请假开始时间')),
                ('holi_out_time', models.TimeField(blank=True, null=True, verbose_name='请假结束时间')),
                ('hoil_last_time', models.FloatField(blank=True, null=True, verbose_name='请假持续时间(天)')),
                ('over_in_time', models.DateTimeField(blank=True, null=True, verbose_name='加班开始时间')),
                ('over_out_time', models.DateTimeField(blank=True, null=True, verbose_name='加班结束时间')),
                ('over_last_time', models.FloatField(blank=True, null=True, verbose_name='加班持续时长(小时)')),
                ('bustravel_start_time', models.TimeField(blank=True, null=True, verbose_name='出差开始时间')),
                ('bustravel_stop_time', models.TimeField(blank=True, null=True, verbose_name='出差结束时间')),
                ('bustravel_last_time', models.FloatField(blank=True, null=True, verbose_name='出差持续时间(天)')),
                ('check_in_result', models.IntegerField(blank=True, choices=[(1, '正常'), (2, '迟到'), (3, '缺卡')], null=True, verbose_name='上班签到结果')),
                ('check_out_result', models.IntegerField(blank=True, choices=[(1, '正常'), (2, '早退'), (3, '缺卡')], null=True, verbose_name='下班签到结果')),
                ('late_time', models.IntegerField(blank=True, null=True, verbose_name='迟到时长')),
                ('leaveearly_time', models.IntegerField(blank=True, null=True, verbose_name='早退时长')),
                ('absence_times', models.IntegerField(blank=True, null=True, verbose_name='缺勤次数')),
            ],
            options={
                'verbose_name': '每日出勤状况表',
                'db_table': 'employee_days_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeHoildayStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoilday_type', models.CharField(choices=[('a', '调休假'), ('b', '事假'), ('c', '病假'), ('d', '婚假'), ('e', '产假'), ('f', '陪产假'), ('g', '哺乳假'), ('h', '节育假'), ('i', '工伤假'), ('j', '看护假'), ('k', '丧假'), ('l', '产检假')], max_length=255, verbose_name='请假类型')),
                ('hoilday_day_type', models.CharField(choices=[(1, '普通工作日请假'), (2, '周六工作日请假'), (3, '周日请假'), (4, '节假日请假')], max_length=255, verbose_name='请假日类型')),
                ('hoilday_start_time', models.TimeField(blank=True, null=True, verbose_name='请假开始时间')),
                ('hoilday_stop_time', models.TimeField(blank=True, null=True, verbose_name='请假结束时间')),
                ('hoilday_last_time', models.FloatField(verbose_name='请假时长(天)')),
                ('years', models.IntegerField(blank=True, null=True)),
                ('months', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('weeks', models.IntegerField(blank=True, null=True)),
                ('dates', models.DateField(blank=True, null=True, verbose_name='请假日期')),
                ('serial', models.CharField(blank=True, max_length=255, null=True, verbose_name='云之家流水号')),
            ],
            options={
                'verbose_name': '请假信息统计表',
                'db_table': 'employee_hoilday_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeMonthStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(blank=True, null=True, verbose_name='考勤年')),
                ('months', models.CharField(max_length=255, verbose_name='考勤月')),
                ('attendance_days', models.FloatField(blank=True, null=True, verbose_name='应出勤(天)')),
                ('act_attendance_days', models.FloatField(blank=True, null=True, verbose_name='实际出勤(天)')),
                ('sat_attendance_days', models.FloatField(blank=True, null=True, verbose_name='周六出勤(天)')),
                ('sun_attendance_days', models.FloatField(blank=True, null=True, verbose_name='周日出勤(天)')),
                ('holi_attendance_days', models.FloatField(blank=True, null=True, verbose_name='节假日出勤(天)')),
                ('evection_days', models.FloatField(blank=True, null=True, verbose_name='出差(天)')),
                ('usua_overtime', models.FloatField(blank=True, null=True, verbose_name='平常加班(时)')),
                ('absence_time', models.FloatField(blank=True, null=True, verbose_name='缺勤时间')),
                ('miss_chock_in_times', models.IntegerField(blank=True, null=True, verbose_name='上班缺卡次数')),
                ('miss_chock_out_times', models.IntegerField(blank=True, null=True, verbose_name='下班缺卡次数')),
                ('late_times', models.IntegerField(blank=True, null=True, verbose_name='迟到次数')),
                ('late_length', models.FloatField(blank=True, null=True, verbose_name='迟到时长(分钟)')),
                ('early_leave_times', models.IntegerField(blank=True, null=True, verbose_name='早退次数')),
                ('early_leave_length', models.FloatField(blank=True, null=True, verbose_name='早退时长(分钟)')),
                ('a_holi', models.FloatField(blank=True, null=True, verbose_name='调休假(天)')),
                ('b_holi', models.FloatField(blank=True, null=True, verbose_name='事假(天)')),
                ('c_holi', models.FloatField(blank=True, null=True, verbose_name='病假(天)')),
                ('d_holi', models.FloatField(blank=True, null=True, verbose_name='婚假(天)')),
                ('e_holi', models.FloatField(blank=True, null=True, verbose_name='产假(天)')),
                ('f_holi', models.FloatField(blank=True, null=True, verbose_name='陪产假(天)')),
                ('g_holi', models.FloatField(blank=True, null=True, verbose_name='哺乳假(天)')),
                ('h_holi', models.FloatField(blank=True, null=True, verbose_name='节育假(天)')),
                ('i_holi', models.FloatField(blank=True, null=True, verbose_name='工伤假(天)')),
                ('j_holi', models.FloatField(blank=True, null=True, verbose_name='看护假(天)')),
                ('k_holi', models.FloatField(blank=True, null=True, verbose_name='丧假(天)')),
                ('l_holi', models.FloatField(blank=True, null=True, verbose_name='产检假(天)')),
                ('act_holi_days', models.FloatField(blank=True, null=True, verbose_name='实际请假(天)')),
                ('overtime_surplus', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '月度信息汇总表',
                'db_table': 'employee_month_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeOvertimeStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_type', models.CharField(choices=[('1', '工作日加班'), ('2', '假日加班'), ('3', '节日加班')], max_length=255, verbose_name='加班类型')),
                ('dates', models.DateField(blank=True, null=True, verbose_name='加班日期')),
                ('overtime_start_time', models.DateTimeField(verbose_name='加班开始时间')),
                ('overtime_stop_time', models.DateTimeField(verbose_name='加班结束时间')),
                ('overtime_last_time', models.FloatField(verbose_name='加班时长(小时)')),
                ('years', models.IntegerField(blank=True, null=True)),
                ('months', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('weeks', models.IntegerField(blank=True, null=True, verbose_name='周几')),
            ],
            options={
                'verbose_name': '员工加班信息汇总表',
                'db_table': 'employee_overtime_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaturdayHoli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField()),
                ('lasttime', models.FloatField()),
                ('date', models.IntegerField()),
            ],
            options={
                'db_table': 'saturday_holi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('bus_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='企业工号')),
                ('namse', models.CharField(max_length=255, verbose_name='员工姓名')),
                ('dept', models.CharField(max_length=255, verbose_name='部门')),
                ('positi', models.CharField(max_length=255, verbose_name='岗位')),
                ('openid', models.CharField(max_length=255)),
                ('time1', models.TimeField(blank=True, null=True, verbose_name='上班打卡时间')),
                ('time2', models.TimeField(blank=True, null=True, verbose_name='午休开始时间')),
                ('time3', models.TimeField(blank=True, null=True, verbose_name='午休结束时间')),
                ('time4', models.TimeField(blank=True, null=True, verbose_name='下班打卡时间')),
                ('att_type', models.IntegerField(blank=True, choices=[(1, '记录考勤'), (2, '不统计考勤')], null=True, verbose_name='出勤类型')),
                ('is_job', models.IntegerField(blank=True, choices=[(1, '在职'), (2, '已离职')], null=True, verbose_name='在职状态')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('is_office', models.IntegerField(blank=True, choices=[(1, '科室人员'), (2, '一线人员')], null=True, verbose_name='人员分类')),
            ],
            options={
                'verbose_name': '员工信息表',
                'db_table': 'employee_information',
                'managed': True,
            },
        ),
    ]
